numero = int(input('Digite um número: '))
print('{} vezes 1 é {}'.format(numero, numero * 1))
print('{} vezes 2 é {}'.format(numero, numero * 2))
print('{} vezes 3 é {}'.format(numero, numero * 3))
print('{} vezes 4 é {}'.format(numero, numero * 4))
print('{} vezes 5 é {}'.format(numero, numero * 5))
print('{} vezes 6 é {}'.format(numero, numero * 6))
print('{} vezes 7 é {}'.format(numero, numero * 7))
print('{} vezes 8 é {}'.format(numero, numero * 8))
print('{} vezes 9 é {}'.format(numero, numero * 9))
