valor = input('Digite algo: ')
print('O tipo de {} é {}'.format(valor, type(valor)))
print('{:.^10} é numérico? {}'.format(valor, valor.isnumeric()))
print('{:/^10} é alfabetico? {}'.format(valor, valor.isalpha()))
print('{:*^10} é ascii? {}'.format(valor, valor.isascii()))
print('{:º^10} é decimal? {}'.format(valor, valor.isdecimal()))
print('{:-^10} é digito? {}'.format(valor, valor.isdigit()))
print('{:%^10} é identificador? {}'.format(valor, valor.isidentifier()))
print('{:@^10} é minusculo? {}'.format(valor, valor.islower()))
print('{:!^10} é imprivel? {}'.format(valor, valor.isprintable()))
print('{:#^10} é espaço? {}'.format(valor, valor.isspace()))
print('{:$^10} é titulo? {}'.format(valor, valor.istitle()))
print('{:¨^10} é maisuculo? {}'.format(valor, valor.isupper()))
print('{:§^10} é alfanumérico? {}'.format(valor, valor.isalnum()))
